// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ai-customer-service/domain"
	"ai-customer-service/internal/cache"
	"ai-customer-service/internal/configs"
	"ai-customer-service/internal/database"
	"ai-customer-service/internal/jwt"
	"ai-customer-service/internal/repositories/csai_repository"
	"ai-customer-service/internal/services/csai_service"
	"ai-customer-service/internal/services/openai_service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewJWT() domain.JWTInterface {
	config := NewConfig()
	jwtInterface := jwt.NewJWT(config)
	return jwtInterface
}

func NewPostgreSQL() *gorm.DB {
	config := NewConfig()
	db := database.NewPostgreSQL(config)
	return db
}

func NewRedis() domain.RedisInterface {
	config := NewConfig()
	redisInterface := cache.NewRedis(config)
	return redisInterface
}

func NewOpenAI() domain.OpenAIInterface {
	config := NewConfig()
	openAIInterface := openai_service.NewOpenAI(config)
	return openAIInterface
}

func NewCSAIRepository() domain.CSAIRepositoryInterface {
	db := NewPostgreSQL()
	csaiRepositoryInterface := csai_repository.NewCSAIRepository(db)
	return csaiRepositoryInterface
}

func NewCSAIService() domain.CSAIServiceInterface {
	redisInterface := NewRedis()
	openAIInterface := NewOpenAI()
	csaiRepositoryInterface := NewCSAIRepository()
	csaiServiceInterface := csai_service.NewCSAIService(redisInterface, openAIInterface, csaiRepositoryInterface)
	return csaiServiceInterface
}

// wire.go:

func NewConfig() *configs.Config {
	return configs.NewConfig()
}
