// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ai-customer-service/domain"
	"ai-customer-service/internal/cache"
	"ai-customer-service/internal/configs"
	"ai-customer-service/internal/database"
	"ai-customer-service/internal/jwt"
)

// Injectors from wire.go:

func NewJWT() domain.JWTInterface {
	config := NewConfig()
	jwtInterface := jwt.NewJWT(config)
	return jwtInterface
}

func NewPostgreSQL() (domain.PostgreSQLInterface, error) {
	config := NewConfig()
	postgreSQLInterface := database.NewPostgreSQL(config)
	return postgreSQLInterface, nil
}

func NewRedis() (domain.RedisInterface, error) {
	config := NewConfig()
	redisInterface := cache.NewRedis(config)
	return redisInterface, nil
}

// wire.go:

func NewConfig() *configs.Config {
	return configs.NewConfig()
}
